### ISSUE TITLE
JSONObject null as string 

### ISSUE THREAD

**Issue by varshavaradarajan** [3pillarlabs/socialauth#101]
If a json response contains null like below:
```
{
    "login":"foo",
    "id":123,
    "name":null,
    "email":null
}
```
Using optString like [here](https://github.com/3pillarlabs/socialauth/blob/master/socialauth/src/main/java/org/brickred/socialauth/provider/GitHubImpl.java#L177) returns null as string for name and email. For more details, please refer to [this](http://stackoverflow.com/questions/18226288/json-jsonobject-optstring-returns-string-null) for details

So, now, one has to check against "null" string and that’s problematic because "null" can be a valid last name.

Fix: Update the json dependency to the latest version: 
```
<!-- https://mvnrepository.com/artifact/org.json/json -->
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20160810</version>
</dependency>

```

**Comment by ketan** [comment]
Can we mark this issue as closed? Thanks.
