### ISSUE TITLE
AccountManager

### ISSUE THREAD

**Issue by sashamirkovic** [3pillarlabs/socialauth#16]
Is it possible if AccountManager has stored authtoken to pass it to SocialAuth without authenticating through SocialAuth login dialog and use stored token in SocialAuth?

**Comment by sayantam** [comment]
@tarun-nagpal I think you fixed it? Please update when you get a chance.

**Comment by sayantam** [comment]
This should be an enhancement to [socialauth-android](https://github.com/3pillarlabs/socialauth-android). Could you please add to that repo?
