### ISSUE TITLE
Hotmail and Yahoo Provider Problem

### ISSUE THREAD

**Issue by BrunoCaxito** [3pillarlabs/socialauth#28]
I'm trying to login with microsoft and it is returning an error.

      error=server_error&error_description=The HTTP request was forbidden with client authentication scheme %27Anonymous%27.

I noticed that hotmail login isn't working at the [3pillarlabs demo](http://labs.3pillarglobal.com/socialauthdemo/registration.do) either

Yahoo! is acting like I have misconfigured something, because socialauth not even send the request
Is there anything wrong here?

     api.login.yahoo.com.consumer_key = My_key_here
     api.login.yahoo.com.consumer_secret = My_secret_here

And the button JavaScript onClick function:

    window.location = "/sign-in.do?provider=yahoo";

Thanks.

**Comment by tarun-nagpal** [comment]
Please re-open this issue if you are facing problem with yahoo.
