### ISSUE TITLE
Google+ provider forwarding to opensource.brickred.com

### ISSUE THREAD

**Issue by buksy90** [3pillarlabs/socialauth#33]
I have run demo on lan (http://192.168.xx.33:8084/socialauthdemo/registration.do) and have changed google+ secret and client id in oauth_consumer.properties

```
#GoolgePlus
googleapis.com.consumer_key=XXXX232041197-XXXXXXXbcchuac8j664fmk8uc5lp421g.apps.googleusercontent.com
googleapis.com.consumer_secret=PNzJPkameXS4snZ08nXXXXXX
```

I have even tried to chance constructor-arg in socialauthdemo-servlet.xml to
```
<constructor-arg value="http://192.168.xx.33:8084/socialauthdemo/" />
```

However, when I click on Google+ icon in registration, I am always redirected to http://opensource.brickred.com/socialauthdemo/socialauth.do?state=SocialAuth1417558005067&code=4/bAutML51cmXeNO1PZ8_VAqoFVvbdwoD1UlXboPoCwHc.UjJHbczR8aYUYFZr95uygvXVPkUalAI&authuser=0&num_sessions=1&session_state=7a79fee70aa03644e2aa7f057ad9d2eb660ac8b0..9dcf&prompt=none

Other providers are rightly redirected to provider's site and asks for authentication.

**Comment by sayantam** [comment]
You should not change the constructor argument, instead create a static DNS mapping for opensource.brickred.com to 127.0.0.1. This is because the keys you are using have opensource.brickred.com as the configured callback URL.
