### ISSUE TITLE
authURL growing indefinitely because of repeated appends of state parameter in static map

### ISSUE THREAD

**Issue by arjantijms** [3pillarlabs/socialauth#34]
SocialAuth 4.7 has started to add a state parameter. This state parameter is appended to a URL, which is subsequently stored in a static map.

Every time a new instance of the SocialAuthManager is created, a new provider instance is also created, which then grabs the URL from the static map, appends the state parameter and stores it back. This causes the URL to grow indefinitely, e.g.

https://accounts.google.com/o/oauth2/auth?state=SocialAuth1417701692349?state=SocialAuth1417701858515?state=SocialAuth1417702054237?state=SocialAuth1417702311307?state=SocialAuth1417702330548?state=SocialAuth1417702366725?state=SocialAuth1417703049503?ad infinitum...

This happens because of the following code:

    private static final Map<String, String> ENDPOINTS;

    String authURL = ENDPOINTS.get(Constants.OAUTH_AUTHORIZATION_URL) + "?" + Constants.STATE + "=" + state;
    ENDPOINTS.put(Constants.OAUTH_AUTHORIZATION_URL, authURL);

See e.g. https://github.com/3pillarlabs/socialauth/blob/master/socialauth/src/main/java/org/brickred/socialauth/provider/GooglePlusImpl.java#L116 for the Google+ provider (other providers do the same thing).

**Comment by ranjaabhishek** [comment]
Has this issue been resolved yet ,quite a big bug

**Comment by tarun-nagpal** [comment]
It is resolved in socialaut-4.8.

**Comment by ranjaabhishek** [comment]
I don't see it available ,is it already available or is it scheduled to be released soon ?

**Comment by ngocdaothanh** [comment]
Version 4.9 has been released. This issue should be closed now?
http://search.maven.org/#search%7Cga%7C1%7Csocialauth
