### ISSUE TITLE
Provider state does not match OAuth endpoints

### ISSUE THREAD

**Issue by valdasraps** [3pillarlabs/socialauth#38]
The problem appears when application creates new Manager object for each client. This is fairly possible with web applications, i.e. session was wiped away, etc.

Some of the Providers now have unique state property generated in constructor. state goes into OAUTH_AUTHORIZATION_URL and (for the first time) is being written to OAuthConfig authenticationUrl property. Consequent Managers have different states BUT get the same the first authenticationUrl from OAuthConfig!!! Eventually authentication for subsequent Managers breaks with

org.brickred.socialauth.exception.SocialAuthException: State parameter value does not match with expected value
        at org.brickred.socialauth.provider.GooglePlusImpl.verifyResponse(GooglePlusImpl.java:189)
        at org.brickred.socialauth.SocialAuthManager.connect(SocialAuthManager.java:184)
        ....

Another related bad thing is in static Manager.ENDPOINTS which is constantly being overwritten by each Manager and then put back from OAuthConfig.

BTW, this issue is related to https://github.com/3pillarlabs/socialauth/issues/34

**Comment by ranjaabhishek** [comment]
Has this issue been resolved yet,i am using version 4.8,still getting :

State parameter value does not match with expected value

**Comment by tarun-nagpal** [comment]
State parameter issue is resolved in socialauth 4.8

**Comment by zratan** [comment]
insert this code after $helper = $fb->getRedirectLoginHelper();

$_SESSION['FBRLH_state']=$_GET['state'];
and it wil work or for more detail visit [facebook login apps](http://zrclassroom.com/toturials/creer-une-application-facebook-connect-php-sdk-v5-207)
