### ISSUE TITLE
No Support for refresh token

### ISSUE THREAD

**Issue by abhitrupti** [3pillarlabs/socialauth#44]
Google plus provides a refresh token, which is currently not being stored anywhere in access grant.
Is there any other place to store it ? And if not then it would be great if it can be added to access grant.

**Comment by abhinav-maheshwari** [comment]
I remember that we did this intentionally, since the AccessGrant is serializable and may be used again, while the refresh token is only valid for some time. Can you help us understand your use case ?

**Comment by tarun-nagpal** [comment]
To get refresh token you need offline access.
To do so just enter following in oauth_consumer.properties file.
googleapis.com.authentication_url=https://accounts.google.com/o/oauth2/auth?access_type=offline

Disconnect your app from google plus and try to connect google plus again.
To disconnect, visit https://plus.google.com/apps

Refresh token will be saved in AccessGrant object, in attributes.

**Comment by tarun-nagpal** [comment]
Closing this issue.
