### ISSUE TITLE
Google auth using deprecated API, will stop working on Mar, 23 2015

### ISSUE THREAD

**Issue by eyforia** [3pillarlabs/socialauth#48]
It looks like google is dropping support for OAuth 2.0. All "sign in with google" log-ins now display the warning message(see screenshot). 

According to Google's documentation, they've started rolling out limitations and will ultimately shut down OAuth 2.0 on Apr 20. The majority of users will lose access after Mar 23 (unless a specific parameter is add ed to the request)

More details here:
https://developers.google.com/accounts/docs/OpenID

Please advise. 

![google-login](https://cloud.githubusercontent.com/assets/10228096/6458609/72df24ca-c153-11e4-956a-7f4b670b660c.png)

**Comment by Chtig** [comment]
I'm considering using socialauth, and this really sounds like a big issue to me :(
Do you intend to do something about it? If yes do you have a rough idea when?

**Comment by eyforia** [comment]
I haven't got any response from 3pillarlabs yet

I'm considering switching to Google's java library for authentication
https://developers.google.com/+/quickstart/java

We'll keep using socialauth for facebook SSO.

**Comment by micheleorsi** [comment]
Same problem also for me, I am thinking the same @eyforia!
Actually this is a really big problem, if I have time I will try to fork this repo and implement the new method

**Comment by shrhoads** [comment]
This I think will completely stop working tomorrow.  Any plans to work on it here?  Anyone forking?

**Comment by micheleorsi** [comment]
I've worked on this two projects in these days:
https://github.com/micheleorsi/gplus-verifytoken-java
https://github.com/micheleorsi/gplus-quickstart-java

I think the first biggest difference with the actual OpenId implementation is the fact that the button is smarter than a simple redirect.
That's why in my opinion is so difficult to integrate with socialauth. For the moment I created an other endpoint that handles this authentication

**Comment by tarun-nagpal** [comment]
We have two providers related to Google. One is Google and other one is GooglePlus.

Google provider was no long in use as we told several times in the issues that If you register your application on google then you'll get the keys for Oaut2.0 which is supported by googleplus provider.

So use googleplus provider and no need to worry. You can also check our demo.
http://labs.3pillarglobal.com/socialauthdemo

In this demo, there are icons for Google and GooglePlus.

Google is not working which was on openid2.0 but googleplus is working fine as it supports OAuth 2.0.

**Comment by puyuan** [comment]
I think the poster meant that OpenID 2.0 will be dropped instead of Oauth 2.0. Oauth 2.0 seems to be working fine, I have been using googleplus provider all the time, and it provides almost the same function as google provider.
