### ISSUE TITLE
Linkedin stopped working

### ISSUE THREAD

**Issue by abhishekranjandev** [3pillarlabs/socialauth#50]
Linkedin provider has stopped working,it is not working even on your sample application hosted on 

http://labs.3pillarglobal.com/socialauthdemo/registration.do

**Comment by sayantam** [comment]
Please upgrade to version 4.9 available from Maven central - the
authentication issue has been fixed. However, LinkedIn has changed the
developer policy, and if you need anything more than auth (like getting
contacts), you have to seek approval from LinkedIn. We have not updated the
demo yet.

cheers!

**Comment by horiworld** [comment]
did you try (or intend) to apply to linkedin partner program for accessing the Connections API? I'm aware I have to manage myself when using your (or any other) lib, just wondering...

**Comment by 3pillarlabs** [comment]
Honestly, that didn't cross our mind. Thank you for the suggestion. We'll
take it up and see the possibilities.

**Comment by abhinav-maheshwari** [comment]
They won't allow us. The documentation days that its only for companies
collecting resumes for hiring.

**Comment by tempestn** [comment]
I'm having this issue as well, and I recognize that I just need to update my current social auth library from version 4.6 to version 4.9. However, the download link for the 4.9 jar file is pointing to the 4.8 version. Can you please let me know where I can download the 4.9 jar? Thanks!

**Comment by horiworld** [comment]
@tempestn not a question of version - try via LinkedIn API Console, read the doc and changes in API and try to applicate to partnership program without hope :((
