### ISSUE TITLE
Your online demo throws an exception on Yahoo! sign in

### ISSUE THREAD

**Issue by keithmarsh** [3pillarlabs/socialauth#52]
1. Navigate to http://labs.3pillarglobal.com/socialauthdemo/
2. Select Yahoo!
3. Provide credentials.  
4. Accept permissions
5. Observe stacktrace below

HTTP Status 500 -

type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:894)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
root cause

java.lang.NullPointerException
	com.threepillar.labs.socialauthsample.controller.SuccessController.registration(SuccessController.java:79)
	com.threepillar.labs.socialauthsample.controller.SuccessController.getRedirectURL(SuccessController.java:65)
	sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.27 logs.

Apache Tomcat/7.0.27

**Comment by sayantam** [comment]
We need to update the demo - will do it soon. Thank you for your attention. cheers!

**Comment by sayantam** [comment]
Demo has been updated

**Comment by keithmarsh** [comment]
I still get the same error at http://labs.3pillarglobal.com/socialauthdemo/authSuccess.do

**Comment by maheshchand** [comment]
We have tried it again and we do not see the error you mentioned. Unless you hit the URL "http://labs.3pillarglobal.com/socialauthdemo/authSuccess.do" directly without going through sing-in page. To get the accurate issue can you please share more specific details like browser and exact steps you are doing...

**Comment by keithmarsh** [comment]
You are correct.  I must have had a cookie saved from the previous version.  Clean browser and all works well.  Apologies.
