### ISSUE TITLE
OpenID for Google is deprecated

### ISSUE THREAD

**Issue by dmfilipenko** [3pillarlabs/socialauth#54]
Trying to use demo. Click on Google it shows me https://support.google.com/accounts/answer/6206245?p=openid&rd=1

**Comment by tarun-nagpal** [comment]
Try Google+ instead of Gmai icon.
Thanx for reminding. We will remove this from demo. Google functionality is working with google+

**Comment by sayantam** [comment]
Google icon removed from demo code base.

**Comment by sayantam** [comment]
Updated demo deployed
