### ISSUE TITLE
Dependency on servlet-api should be <scope>provided</scope>

### ISSUE THREAD

**Issue by tmortagne** [3pillarlabs/socialauth#56]
For example when building a WAR with socialauth as dependency servlet-api jar ends up in the WAR which does not make much sense since this is applcation server's job. Usually things like servlet dependency are made <scope>provided</scope> in Maven.

Would be great if this could be fixed on your side to avoid crappy excludes.

**Comment by stefanbaritchii** [comment]
Will do the change. Thanks for pointing that out

**Comment by tmortagne** [comment]
Thanks for that lighting fast response :)

**Comment by stefanbaritchii** [comment]
changes have been commited and merged into master. please let me know if it's ok now.

**Comment by tmortagne** [comment]
Looks good to me.

By the way on a different subject you should probably put 2.5 instead of [2.5,) otherwise your jar is built with last servlet-api version while it would probably be safer to build it with the lowest version you want to support.

**Comment by sayantam** [comment]
Thanks, you are right. This has been incorporated for next release.
