### ISSUE TITLE
How to get email for facebook using Social Auth 4.9

### ISSUE THREAD

**Issue by tanmoy-hl** [3pillarlabs/socialauth#59]
Hi,
I am using Social auth 4.9 in a dropwizard project and I am trying to retrieve user email id.
I found a reference here where the firstname, lastname, email etc are explicitly set to null.
https://github.com/3pillarlabs/socialauth/blob/master/socialauth/src/main/java/org/brickred/socialauth/provider/FacebookImpl.java

My code goes as follows {recommended way to get the info}: 
Map<String, String> params = SocialAuthUtil.getRequestParametersMap(request)
                AuthProvider provider = manager.connect(params);
                ResponseUserModel respModel = null;
                // get profile
                Profile p = provider.getUserProfile();
                String email = p.getEmail();

##############################################################################
here I get null for the email. The object I get is as follows : 
'org.brickred.socialauth.Profile Object {
 email: null
 firstName: null
 lastName: null
 country: null
 language: null
 fullName: Tanmoy Bhattacharjee
 displayName: null
 dob: null
 gender: null
 location: null
 validatedId: 1#############8
 profileImageURL: http://graph.facebook.com/1#############8/picture
 providerId: facebook
 contactInfo { 
 } 
}'

##############################################################################

I am stuck here for long. Any help will be appreciated.

Thanks,
Tanmoy

**Comment by stefanbaritchii** [comment]
Hi,

What happens if you use the demo with the account that you try to get the email from?

Cheers,
Stefan

**Comment by tanmoy-hl** [comment]
There I can see the email, country. language, gender etc.

Thanks,
Tanmoy

**Comment by tanmoy-hl** [comment]
Any update on this issue? Any resolution for the problem that I am facing?

**Comment by bogdan-nourescu** [comment]
In order for me to get the email address  from facebook i had to add to the oauth_consumer.properties:
`graph.facebook.com.custom_permissions = email`

**Comment by isaquexavier** [comment]
Hi there,

I am facing the same problem, someone has any update on this issue? Any resolution for the problem that I am facing?

Thanks!

**Comment by duongminh07** [comment]
This is due to a change in Facebook api 2.4. Now you need to specify individual fields to fetch. The request URL should be e.g. https://graph.facebook.com/v2.4/me?access_token=<access token>&fields=email,language,dob,gender. Currently the request url is https://graph.facebook.com/v2.2/me?access_token=<access token>. 

I think this should be resolved soon but don't know when. For temporary workaround maybe just change the code by yourself

**Comment by sayantam** [comment]
Isn't this solved if you use custom scopes?

**Comment by duongminh07** [comment]
I believe custom scopes is for permissions .. you get the permission to access public_profile .. but after that you need to send another GET request (manager.connect()) with the access token to get the data you want. At that point you need to specify what to fetch. And what to fetch is a subset of the custom scope

Please refer to Choosing fields section https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4

**Comment by sayantam** [comment]
Thanks all. We'll take a look at the end of this week. Right now our work
commitments have us bogged down.

**Comment by isaquexavier** [comment]
Hi Guys,

About this problem, there is a fork from jolivares which fixes it and also another problem related to read_stream permission #60 . Could you guys from 3pillarlabs check this implementation and validate in order to release a fixed version, I have tested and worked fine to me.

> Fixed Class (FacebookImpl)
https://github.com/jolivares/socialauth/commit/ffb2be3000c9ca0ad2a66f15fce4dc15b6aab722
https://github.com/3pillarlabs/socialauth/network

@sayantam In my case I need some properties/fields from the user's profile, using the custom scopes didn't solve it.

Thanks a lot !

**Comment by sayantam** [comment]
Thanks for the notes, everyone!

Yep, we will check it soon enough and do the needful.

**Comment by tanmoy-hl** [comment]
I have checked as well, https://github.com/jolivares/socialauth/commit/ffb2be3000c9ca0ad2a66f15fce4dc15b6aab722 
The above one works fine.

A stable version in Maven repo would be very helpful.

**Comment by sayantam** [comment]
The Facebook implementation is based on FB API 2.2 and needs to be upgraded to 2.4 - this has been recorded as a separate ticket. Meanwhile, if you wish to use the FB API 2.4, please consider using a socialauth plugin - please refer to [this wiki page] (https://github.com/3pillarlabs/socialauth/wiki/How-To-Write-Custom-Plugin-In-SocialAuth).

**Comment by isaquexavier** [comment]
Hi Sayantam,

Do you know when this upgrade to 2.4 version will be released?

Thanks.

**Comment by superch999** [comment]
Hi Sayantam / 3Pillar Global,

Any updates on having a stable release with this fix?

Thank you.

**Comment by sayantam** [comment]
Guys,

I will do it before the end of this week.

cheers
Sayantam

**Comment by superch999** [comment]
Thanks in advance, Sayantam!
