### ISSUE TITLE
Did yahoo stop providing email addresses?

### ISSUE THREAD

**Issue by bogdan-nourescu** [3pillarlabs/socialauth#61]
Since today, 22.09.2015 i stopped receiving the email address when i try to login with yahoo.
I get the emails property in the JSON, but it is always an empty array. I didn't change anything to my application, and yesterday it was working.
If you go to [here](https://developer.yahoo.com/yql/console/?_uiFocus=social&q=select%20*%20from%20social.profile%20where%20guid%3Dme%3B)
it works, it shows the email address, but not in the request.

I am using version 4.9.

**Comment by sayantam** [comment]
I confirmed the behavior. This is strange. I don't know of an announcement
from Yahoo to this effect. We will have to check this.

**Comment by bogdan-nourescu** [comment]
It seems that now they supply the email address in the JSON.
I think it was a transient error from yahoo
