### ISSUE TITLE
 "Invalid Scopes: read_stream." for Facebook

### ISSUE THREAD

**Issue by swapps** [3pillarlabs/socialauth#69]
i'm getting this error while using socialauth "Invalid Scopes: read_stream." for Facebook

**Comment by abhinav-maheshwari** [comment]
Resolved now.

**Comment by swapps** [comment]
what do you mean by Resolved now ? i'm still getting this error

**Comment by abhinav-maheshwari** [comment]
Resolved means that code has been merged for this, you can take the latest
code from github repo and do the build.

**Comment by swapps** [comment]
without the new jar how can i add this to my project ? i tried to import as a module in Android Studio but it doesn't work

**Comment by abhinav-maheshwari** [comment]
You will need to run the gradle build to create the socialauth jar. Jars
are only released periodically for a new version.

**Comment by swapps** [comment]
Great, thanks for your help
