### ISSUE TITLE
Facebook error : java.lang.NullPointerException

### ISSUE THREAD

**Issue by swapps** [3pillarlabs/socialauth#70]
Hi, i'm getting this issue when i try to update status on Facebook. My code is working fine for Twitter.

java.lang.NullPointerException: Attempt to invoke interface method 'org.brickred.socialauth.util.Response org.brickred.socialauth.AuthProvider.updateStatus(java.lang.String)' on a null object reference
Authentication Error: Message Not Posted

any idea ?

**Comment by abhinav-maheshwari** [comment]
You might not be storing the provider in session ?

**Comment by swapps** [comment]
What do you mean ?

**Comment by swapps** [comment]
Could you help me, i have done some research and i didn't found how to store this in android

**Comment by abhinav-maheshwari** [comment]
Have you taken a look at SocialAuth Android ? If not, please do. The
socialauth on server side and client side works a bit differently.

In Android, what we do is launch a browser and redirect the user to the
OAuth link of Facebook etc. At that point Facebook asks for authentication
and redirects the browser along with an OAuth token in the URL. At that
point, we take over the browser and read the OAuth token from it to create
the AuthProviders.

Please refer to the source code of SocialAuth android, it will be helpful.
Or you can consider using SocialAuth Android itself.
https://github.com/3pillarlabs/socialauth-android/blob/master/socialauth-android/src/org/brickred/socialauth/android/SocialAuthDialog.java

**Comment by swapps** [comment]
thanks, i'm using SocialAuth android indeed i ask my question on their git
