### ISSUE TITLE
The 4.10 maven artifact doesn't contain 4.10 code

### ISSUE THREAD

**Issue by annorax** [3pillarlabs/socialauth#73]
For example, take a look at FacebookImpl.java, and note that in the maven src artifact's sources jar (socialauth-4.10-sources.jar), the recently added constant PROFILE_FIELDS is absent, which means that this source file is from an earlier version.

**Comment by sayantam** [comment]
Okay - will check this out.

**Comment by noamho** [comment]
This is pertinent since the latest `FacebookImpl` fixes are not included in the last version.

**Comment by noamho** [comment]
@sayantam, any updates?

**Comment by sayantam** [comment]
I just uploaded the updated artifact to Nexus - should be available from Central in a couple of hours.

**Comment by sayantam** [comment]
The updated artifact is available from Maven Central. Thank you for pointing out the issue.

**Comment by noamho** [comment]
Thanks @sayantam
